name: CI/CD

on:
  push:
    branches: [ backendworkflow ]
  pull_request:
    branches: [ backendworkflow ]

defaults:
  run:
    working-directory: Backend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v16.15.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: pytest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
